// src/main/angular/src/app/panel-tetris/panel-tetris.component.ts
import { Component, Output, EventEmitter, Input } from '@angular/core';
import axios from 'axios';
import io, { Socket } from 'socket.io-client';

import { ApiService } from '../api-service.service';
import { Board, Caja, Figura } from '../app.component';

import SERVERNAME from '../servername.json'

import { initialBoard } from '../ventana-principal/ventana-principal.component';

@Component({
  selector: 'div.panel-tetris',
  templateUrl: './panel-tetris.component.html',
  styleUrls: ['./panel-tetris.component.css']
})
export class PanelTetrisComponent {

  @Input() fallingFigure : Figura | undefined;
  @Input() figuresFixed : Caja[] = [];
  @Input() board : Board = initialBoard;
  @Input() setBoard : Function = () => {};
  @Input() setIntervalId : Function = () => {};
  @Input() timer : NodeJS.Timer[] = [];

  apiService: ApiService;
  socket: Socket | undefined;

  constructor( apiService : ApiService ) {
    this.apiService = apiService;
  }

  ngOnInit() {
    this.apiService.fetchBoard(this.board,this.setBoard,this.timer);

    const boardListener = (boardCad: string) => {
      //console.log('board from rabbitmq = ' + boardCad );
      if( this.board.running && !this.board.paused ) {
        const boardObj = JSON.parse(boardCad);
        this.setBoard( boardObj );
      }
    };

    this.socket = io( SERVERNAME.node_rabbitmq_address ,{
      reconnection: true
    });

    this.socket.on('board', boardListener);
    this.socket.on('connect_error', err =>  {});
    this.socket.on('connect_failed', err => {});
    this.socket.on('disconnect', err => {});
  }

  ngOnDestroy() {
    if ( this.socket ) this.socket.close();
  }
}

<div *ngIf="board.running && !board.paused">
    <div *ngFor="let box of fallingFigure?.listBoxes">
        <app-box [caja]="box"></app-box>
    </div>
    <div *ngFor="let box of figuresFixed">
        <app-box [caja]="box"></app-box>
    </div>
</div>
<div class="message" *ngIf="!board.running && !board.gameOver">
    <div class="hitEnterLabel">HIT ENTER</div>
</div>
<div class="message" *ngIf="board.running && board.paused">
    <div class="pausedLabel">PAUSED</div>
</div>
<div class="message" *ngIf="board.gameOver">
    <div class="gameOverLabel">GAME OVER</div>
</div>

// src/main/react/src/components/PanelTetris/PanelTetris.tsx
import { useContext, useState, useEffect } from 'react';
import { ApiServiceContext, Game } from '../../App';
import Box from '../Box/Box';
import Figure from '../Figure/Figure';

import "./panelTetris.css";

const renderHitEnter = () => {
  return <div className="message"><div className="hitEnterLabel">HIT ENTER</div></div>;
}

const renderGameOver = () => {
  return <div className="message"><div className="gameOverLabel">GAME OVER</div></div>;
}

const renderPaused = () => {
  return <div className="message"><div className="pausedLabel">PAUSED</div></div>;
} 

const renderFigures = ( context : Game ) => {
  const [board] = context.board;
  const figuraCayendo = board.fallingFigure;
  const cajas = board.figuresFixed;
  const first = figuraCayendo? <Figure listBoxes={figuraCayendo.listBoxes} hashBoard={figuraCayendo.hashBoard}/>: <></>;
  const second = cajas.map( box => <Box key={box.x+"-"+box.y} caja={box}/> );
  return <>{first}{second}</>
}

const PanelTetris = () => {
  const context = useContext(ApiServiceContext);
  context.intervalFetch = useState<NodeJS.Timer>();
  const apiService = context.apiService;
  const socket = context.socket[0];
  const [board,setBoard] = context.board;
  useEffect(() => {
    const boardListener = (boardCad: string) => {
      console.log('board from rabbitmq = ' + boardCad );
      if( board.running && !board.paused ) {
        const boardObj = JSON.parse(boardCad);
        setBoard( boardObj );
      }
    };
    const hashListener = (hashCad: string) => {
      console.log('hash from rabbitmq = ' + hashCad );
      if( board.running && !board.paused ) {
        const hash = JSON.parse(hashCad);
        setBoard( {...board, hash: hash} );
      }
    };
    const figuresListener = (figuresCad: string) => {
      console.log('figures from rabbitmq = ' + figuresCad );
      if( board.running && !board.paused ) {
        const figures = JSON.parse(figuresCad);
        if( figures ) {
          setBoard( {...board, figuresFixed: figures} );
        }
      }
    };
    const figureFallingListener = (figureFallingCad: string) => {
      console.log('figureFalling from rabbitmq = ' + figureFallingCad );
      if( board.running && !board.paused ) {
        const figureFalling = JSON.parse(figureFallingCad);
        if( figureFalling ) {
          setBoard( {...board, fallingFigure: figureFalling} );
        }
      }
    };
    if( socket ) socket.on('board', boardListener);
    if( socket ) socket.on('hash', hashListener);
    if( socket ) socket.on('figures', figuresListener);
    if( socket ) socket.on('figure_falling', figureFallingListener);
    return () => {
      if( socket ) socket.off('board', boardListener);
      if( socket ) socket.off('hash', hashListener);
      if( socket ) socket.off('figures', figuresListener);
      if( socket ) socket.off('figure_falling', figureFallingListener);
    };
  }, [context,board,setBoard,board.running,board.paused,socket]);
  useEffect(() => {
    apiService.fetchBoard(context);
    if( !board.running || board.paused ) {
      if( context.intervalFetch[0] ) clearInterval(context.intervalFetch[0]);
    }
  }, [context,apiService,board.running,board.paused]);
  return (
    <div className="panelTetris">
      {board.running?
        (board.paused? renderPaused(): renderFigures(context)):
        (board.gameOver? renderGameOver(): renderHitEnter())}
    </div>
  );
}

export default PanelTetris;
