// src/main/react/src/components/VentanaPrincipal/VentanaPrincipal.tsx
import { useEffect, useRef, KeyboardEvent, useContext, useState } from 'react';
import { ApiServiceContext } from '../../App';
import PanelLateral from '../PanelLateral/PanelLateral';
import PanelTetris from '../PanelTetris/PanelTetris';

import "./ventanaPrincipal.css";

const VentanaPrincipal = () => {
  const context = useContext(ApiServiceContext);
  const apiService = context.apiService;
  const setFigureFalling = context.figuraCayendo[1];
  const [running,setRunning] = context.running = useState<boolean>(false);
  const [,setPaused] = context.paused = useState<boolean>(false);
  const [hash] = context.hash = useState<number>(0);
  const handleKeyboard = (e: KeyboardEvent): void => {
    switch (e.code) {
      case "Enter":
        if( !running ) {
          apiService.start(setRunning,setPaused);
        } else {
          apiService.pause(setPaused,setRunning);
        }
        break;
      case "Space":
        apiService.space(setFigureFalling,hash);
        break;
      case "ArrowLeft":
        apiService.left(setFigureFalling,hash);
        break;
      case "ArrowRight":
        apiService.right(setFigureFalling,hash);
        break;
      case "ArrowUp":
        apiService.up(setFigureFalling,hash);
        break
      case "ArrowDown":
        apiService.down(setFigureFalling,hash);
        break
    }
  }
  const focusDiv : React.RefObject<HTMLDivElement> = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if(focusDiv.current) focusDiv.current.focus(); 
   }, [focusDiv]);
  return (
    <div className="ventanaPrincipal" tabIndex={0} ref={focusDiv} onKeyDown={handleKeyboard}>
      <PanelTetris/>
      <PanelLateral/>
    </div>
  );
}

export default VentanaPrincipal;

// src/main/angular/src/app/ventana-principal/ventana-principal.component.ts
import { Component, HostListener } from '@angular/core';
import { ApiService } from '../api-service.service';
import { Board } from '../app.component';

export const initialBoard : Board = {
  running:false, paused:false, gameOver:false, fallingFigure:undefined, figuresFixed:[], score:0, hash:0
};

@Component({
  selector: 'div.ventana-principal',
  templateUrl: './ventana-principal.component.html',
  styleUrls: ['./ventana-principal.component.css']
})
export class VentanaPrincipalComponent {

  board : Board = initialBoard;
  timer : NodeJS.Timer[] = [];

  private apiService : ApiService;

  constructor( apiService : ApiService ) {
    this.apiService = apiService;
    this.setRunning = this.setRunning.bind(this);
    this.getRunning = this.getRunning.bind(this);
    this.setBoard = this.setBoard.bind(this);
    this.setPaused = this.setPaused.bind(this);
  }

  setRunning( running : boolean ) {
    this.board.running = running;
  }

  setPaused( paused : boolean ) {
    this.board.paused = paused;
  }

  getRunning() {
    return this.board.running;
  }

  setBoard( board : Board ) {
    this.board = board;
  }

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) { 
    switch (event.code) {
      case "Enter":
        if( !this.getRunning() ) {
          this.apiService.start( this.board, this.setBoard, this.setRunning, this.timer );
        } else {
          this.apiService.pause( this.board, this.setBoard, this.setPaused, this.timer );
        }
        break;
      case "Space":
        this.apiService.space( this.board );
        break;
      case "ArrowLeft":
        this.apiService.left( this.board );
        break;
      case "ArrowRight":
        this.apiService.right( this.board );
        break;
      case "ArrowUp":
        this.apiService.up( this.board );
        break
      case "ArrowDown":
        this.apiService.down( this.board );
        break
    }
  }

  ngOnInit() {
  }
}

<div class="panel-tetris" tabIndex={0}
    [fallingFigure]="board.fallingFigure"
    [figuresFixed]="board.figuresFixed"
    [board]="board"
    [setBoard]="setBoard"
    [timer]="timer">
</div>
