// src/main/angular/src/app/box/box.component.ts
import { Component, Input } from '@angular/core';

import { Caja } from '../app.component'

@Component({
  selector: 'app-box',
  templateUrl: './box.component.html',
  styleUrls: ['./box.component.css']
})
export class BoxComponent {

  @Input() caja: Caja | undefined;

}

<div [className]="'box'"
     [style.top.px]="caja?.y"
     [style.left.px]="caja?.x"
     [style.background]="caja?.color">
</div>

// src/main/react/src/components/Box/Box.tsx
import React from 'react';

import "./box.css";

export interface Caja {
  x: number
  y: number
  color: string
}

type BoxProps = {
  caja: Caja;  
}

const Box = ( {caja} : BoxProps ) =>  (
  <div className="box" style={{top: caja.y, left: caja.x, backgroundColor: caja.color }}></div>
);

export default Box;
